---
    name: RSpec
    on: push
    jobs:
      build:
        runs-on: ubuntu-18.04
        steps:
        - name: Checkout branch
          uses: actions/checkout@v1
        - name: Cache Ruby Install
          uses: actions/cache@v1
          id: ruby-install-cache
          with:
            path: "~/local/rubies"
            key: ruby-2.6.5
        - name: Install Ruby
          uses: clupprich/ruby-build-action@master
          id: ruby
          with:
            ruby-version: 2.6.5
            cache-available: "${{ steps.ruby-install-cache.outputs.cache-hit == 'true'
              }}"
        - name: Cache gems
          uses: actions/cache@v1
          with:
            path: vendor/bundle
            key: "${{ runner.OS }}-gem-cache-${{ hashFiles('**/there_was_an_attempt.gemspec')
              }}"
            restore-keys: "${{ runner.OS }}-gem-cache-\n"
        - name: Install bundler
          run: (bundler -v | grep "2.0.2") || gem install bundler:2.0.2
        - name: Install gems
          run: bundle install --jobs $(nproc) --retry 3 --without metrics --path vendor/bundle
        - name: Run RSpec test suite
          run: bundle exec rspec spec
